// TMBA v0.9.4-A – AirPlay configuration for HiFiBerry Amp4 Pro.
general =
{
    name = "TMBA";
    output_backend = "alsa";
    interpolation = "soxr";
    volume_control_profile = "standard";
};

alsa =
{
    output_device = "hw:CARD=sndrpihifiberry,DEV=0";
    mixer_control_name = "Digital";
    mixer_device = "hw:CARD=sndrpihifiberry";
};

metadata =
{
    enabled = "yes";
    include_cover_art = "no";
    pipe_name = "/run/tmba/shairport-metadata";
    pipe_timeout = 5000;
};
