"""Runtime configuration and diagnostics for shairport-sync on TMBA hosts."""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable, Sequence


@dataclass(frozen=True, slots=True)
class AirPlayRuntimeConfig:
    """Host-specific settings used to render shairport-sync.conf."""

    receiver_name: str = "TMBA"
    output_device: str = "hw:sndrpihifiberry"
    mixer_control: str | None = "Digital"
    mixer_device: str | None = "hw:sndrpihifiberry"
    service_name: str = "shairport-sync.service"
    config_path: str = "/etc/shairport-sync.conf"

    def __post_init__(self) -> None:
        if not self.receiver_name.strip():
            raise ValueError("receiver_name darf nicht leer sein.")
        if not self.output_device.strip():
            raise ValueError("output_device darf nicht leer sein.")
        if not self.service_name.strip():
            raise ValueError("service_name darf nicht leer sein.")
        if not self.config_path.strip():
            raise ValueError("config_path darf nicht leer sein.")

    def render(self) -> str:
        """Render a conservative ALSA configuration for shairport-sync."""

        lines = [
            "// Generated by TMBA. Manual edits may be overwritten.",
            "general =",
            "{",
            f'    name = "{_escape(self.receiver_name.strip())}";',
            '    output_backend = "alsa";',
            "    interpolation = \"soxr\";",
            "    volume_control_profile = \"standard\";",
            "};",
            "",
            "alsa =",
            "{",
            f'    output_device = "{_escape(self.output_device.strip())}";',
        ]
        if self.mixer_control:
            lines.append(
                f'    mixer_control_name = "{_escape(self.mixer_control.strip())}";'
            )
        if self.mixer_device:
            lines.append(
                f'    mixer_device = "{_escape(self.mixer_device.strip())}";'
            )
        lines.extend(["};", "", "metadata =", "{", "    enabled = \"yes\";", "};", ""])
        return "\n".join(lines)


@dataclass(frozen=True, slots=True)
class AirPlayRuntimeReport:
    """Side-effect-free readiness report for an AirPlay host."""

    ready: bool
    binary_found: bool
    config_found: bool
    service_available: bool
    avahi_active: bool
    alsa_device_found: bool
    binary_path: str | None = None
    config_path: str | None = None
    error: str | None = None

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


CommandRunner = Callable[[Sequence[str]], subprocess.CompletedProcess[str]]


class AirPlayRuntimeInspector:
    """Inspect host prerequisites without modifying the system."""

    def __init__(
        self,
        *,
        executable_finder: Callable[[str], str | None] | None = None,
        command_runner: CommandRunner | None = None,
        path_exists: Callable[[str], bool] | None = None,
        timeout_seconds: float = 5.0,
    ) -> None:
        if timeout_seconds <= 0:
            raise ValueError("timeout_seconds muss größer als null sein.")
        self._finder = executable_finder or shutil.which
        self._runner = command_runner or self._run
        self._exists = path_exists or (lambda value: Path(value).is_file())
        self._timeout_seconds = float(timeout_seconds)

    def inspect(self, config: AirPlayRuntimeConfig) -> AirPlayRuntimeReport:
        binary_path = self._finder("shairport-sync")
        config_found = self._exists(config.config_path)
        service_available = self._systemctl_success(
            ["show", config.service_name, "--property=LoadState", "--value"]
        )
        avahi_active = self._systemctl_success(
            ["is-active", "--quiet", "avahi-daemon.service"]
        )
        alsa_device_found = self._alsa_device_exists(config.output_device)

        ready = all(
            (
                binary_path is not None,
                config_found,
                service_available,
                avahi_active,
                alsa_device_found,
            )
        )
        missing: list[str] = []
        if binary_path is None:
            missing.append("shairport-sync")
        if not config_found:
            missing.append(config.config_path)
        if not service_available:
            missing.append(config.service_name)
        if not avahi_active:
            missing.append("avahi-daemon.service")
        if not alsa_device_found:
            missing.append(config.output_device)

        return AirPlayRuntimeReport(
            ready=ready,
            binary_found=binary_path is not None,
            config_found=config_found,
            service_available=service_available,
            avahi_active=avahi_active,
            alsa_device_found=alsa_device_found,
            binary_path=binary_path,
            config_path=config.config_path if config_found else None,
            error=("Nicht bereit: " + ", ".join(missing)) if missing else None,
        )

    def _systemctl_success(self, arguments: Sequence[str]) -> bool:
        executable = self._finder("systemctl")
        if executable is None:
            return False
        try:
            result = self._runner([executable, *arguments])
        except (OSError, subprocess.TimeoutExpired):
            return False
        return result.returncode == 0 and result.stdout.strip() not in {"not-found", "masked"}

    def _alsa_device_exists(self, configured_device: str) -> bool:
        executable = self._finder("aplay")
        if executable is None:
            return False
        try:
            result = self._runner([executable, "-L"])
        except (OSError, subprocess.TimeoutExpired):
            return False
        if result.returncode != 0:
            return False
        target = configured_device.strip()
        candidates = {target}
        if target.startswith("hw:"):
            candidates.add(target.removeprefix("hw:"))
        normalized = re.sub(r"\s+", "", result.stdout)
        return any(re.sub(r"\s+", "", candidate) in normalized for candidate in candidates)

    def _run(self, command: Sequence[str]) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            list(command),
            check=False,
            capture_output=True,
            text=True,
            timeout=self._timeout_seconds,
        )


def write_airplay_config(
    destination: str | Path,
    config: AirPlayRuntimeConfig,
) -> Path:
    """Write a rendered config atomically enough for deployment tooling."""

    path = Path(destination)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(config.render(), encoding="utf-8")
    temporary.replace(path)
    return path


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
