volume:
  startup: 25
  maximum: 90
  minimum: 0
  step: 2
  restore_last: true

player:
  default_source: webradio
  backend: mpd

hardware:
  output_device: hifiberry
  alsa_device: hw:CARD=sndrpihifiberry,DEV=0
  sample_rate: 48000
  channels: 2
  sample_format: S16_LE
